### PR TITLE
Fix: Error using Chinese path

### PR DESCRIPTION
**Pull request by YunHerry**
fix issue: (#1030)

### CODE REVIEW

**Comment by ryanheise** [comment]
I don't believe this is the correct solution. For Windows, I think the `Uri` should be created with `Uri.file(s, windows: true)`.

**Comment by YunHerry** [comment]
in debugging, the value of `_uri.toString()` in `_toMessage` method is not a correct value. although I used `Uri.file(s, windows: true)`, but the value of uri is stiil incorrect in debug. the value I get from `_uri.toString()` is file:///E:/music_cache/%E4%B8%AD.ogg, but, what I want is file:///E:/music_cache/中.ogg
d1593eb0c3ba0c2a834edb0b3afe382f

**Comment by ryanheise** [comment]
Why would you want it to be `file:///E:/music_cache/中.ogg`? That is not a valid URI according to the standard, so it should not be done.

**Comment by YunHerry** [comment]
it may not comply with the standard, but it's difficult for us to predict the file names of the user's environment

**Comment by ryanheise** [comment]
This is not about predicting file names, `中.ogg` is a valid and correct filename. The solution is simply to convert a valid URI into a valid filename on the platform side.

**Comment by YunHerry** [comment]
how should we solve this conversion problem

**Comment by ryanheise** [comment]
When I say the "platform side", I am referring to the native implementation for the platform. You can see how I have implemented it for iOS  (one objective C) and Android (in Java), but the windows implementation is not provided by this repository, it is provided by whichever additional plugin you are using. Which plugin are you using to provide the windows implementation? That is where you will find the platform side of the implementation where it takes the valid Uri and tries to convert that into whatever the platform requires.

If the Uri is not valid in the first place, then we need to fix that first here in just_audio, but then the conversion to the platform side happens in the other plugin that provides the windows platform implementation.

**Comment by YunHerry** [comment]
All plugins communicate based on `_ToMessage()`, why not transcode it in this library, but convert it in the plugin?

**Comment by ryanheise** [comment]
I'm sorry I don't understand what you're referring to by the distinct terms plugin and library which seem the same. However, I can't introduce breaking changes to the platform interface, a Uri is the correct platform independent representation of a resource, and it is still up to the specific platform implementation to handle it in it's own way.

**Comment by ryanheise** [comment]
I assume you are using [just_audio_windows](https://github.com/bdlukaa/just_audio_windows/tree/master/just_audio_windows) to implement the platform side? If so, digging into the [source code](https://github.com/bdlukaa/just_audio_windows/blob/master/just_audio_windows/windows/player.hpp) I see it takes the URI you give it and handles it on the platform in this way:

```cpp
  /**
  * Creates a single MediaSource.
  */
  MediaSource AudioPlayer::createMediaSource(const flutter::EncodableMap& source) const& {
    const std::string* type = std::get_if<std::string>(ValueOrNull(source, "type"));
    if (type->compare("progressive") == 0 || type->compare("dash") == 0 || type->compare("hls") == 0) {
      const auto* uri = std::get_if<std::string>(ValueOrNull(source, "uri"));
      return MediaSource::CreateFromUri(
        Uri(TO_WIDESTRING(*uri))
      );
    } else {
      throw std::invalid_argument("Source is unsupported or can not be nested: " + *type);
    }
  }
```

So it is letting the Windows API directly handle the URI. From the documentation I have seen, Chinese characters should be URL-encoded. I believe that is true, but if it is not, any further rewriting of the URI to work around Window's non-standard handling of URIs will need do be done in the just_audio_windows package rather than this one.

What I can do over here in just_audio is possibly add a `bool windows` parameter to `setFilePath`, although in the meantime, users can instead construct their own Uri via `setAudioSource`.

I would be interested to learn of any progress you make.

**Comment by canxin121** [comment]
> All plugins communicate based on `_ToMessage()`, why not transcode it in this library, but convert it in the plugin?

我认为实际上这应该是WinRT的bug，而不是dart的Uri的问题，估计很快可以打个补丁修上

**Comment by ryanheise** [comment]
@canxin121 do you have a preference on whether the `windows: true` parameter on the Dart side is preferable?

**Pull request closed without merging**
