### PR TITLE
[Changes iOS implementation] Add HTTPS 

### PR DESCRIPTION
**Pull request by raveesh-me**
This is work we did in response to  #99.
#105 seems similar

This solution is not necessarily compatible. Especially the iOS implementation, but we hope this helps you add a new feature.

### CODE REVIEW

**Comment by ryanheise** [comment]
Thanks, @raveesh-me . This is definitely helpful, particularly as I was not familiar with the relevant iOS API.

For reasons unknown, #99 was closed, but I will take #105 as the relevant issue since it is still open.

**Comment by raveesh-me** [comment]
> For reasons unknown, #99 was closed, but I will take #105 as the relevant issue since it is still open.
#99 was closed because we fixed it for them.
#105 can still use our fork for the meanwhile

>  I was not familiar with the relevant iOS API.
Our implementation uses a private call which is not documented in the iOS development docs. So I guess for this one even Apple is not aware of the relevant APIs on the iOS side. :-p

**Comment by ryanheise** [comment]
> #99 was closed because we fixed it for them.

Ah, thanks for explaining that. So "Biswajit Behera" in the git logs owns the contributions, or is it cookytech? (I ask in relation to section D6 of the GitHub terms of service.)

> > I was not familiar with the relevant iOS API.
> 
> Our implementation uses a private call which is not documented in the iOS development docs. So I guess for this one even Apple is not aware of the relevant APIs on the iOS side. :-p

Oh, that does complicate things, since the Apple developer license agreement may prevent anyone from using this plugin if it uses undocumented APIs. I may need to implement an alternative such as creating a local HTTP proxy on device. This may make my previous question mute.

**Comment by raveesh-me** [comment]
>Ah, thanks for explaining that. So "Biswajit Behera" in the git logs owns the contributions, or is it cookytech? (I ask in relation to section D6 of the GitHub terms of service.)

"Cookytech" will be the owner.

> Oh, that does complicate things, since the Apple developer license agreement may prevent anyone from using this plugin if it uses undocumented APIs. I may need to implement an alternative such as creating a local HTTP proxy on device. This may make my previous question mute.

Oh!

**Comment by ryanheise** [comment]
I've implemented a partial proxy-based solution in the latest commit, so I'll close this.

**Pull request closed without merging**
