### PR TITLE
SkipSilence and volume boost options for Android

### PR DESCRIPTION
**Pull request by subhash279**
I implemented the above for Android. It seems more involved iOS side. So someone with more ObjectiveC experience can probably take it up in future.
Please let me know if anything else is needed.

### CODE REVIEW

**Comment by ryanheise** [comment]
Thanks! I'm currently in the process of converting this plugin into a federated plugin which I will commit first, so we will have to resolve the clash after that.

**Comment by subhash279** [comment]
sure thanks!

**Comment by ryanheise** [comment]
Hi @subhash279 

I've just finished the conversion to a federated plugin with a description of the changes in the following comment:

https://github.com/ryanheise/just_audio/issues/103#issuecomment-699614173

Under the new model, it is necessary to also add corresponding methods to the platform interface, and following the style of the other methods, each method in the interface would take a single message as a parameter and return a single message as a result. The web implementation just implements this interface directly while iOS and Android use the method channel version.

**Comment by subhash279** [comment]
@ryanheise pls close this PR as I submitted another one which is in sync with latest plugin changes #234

**Pull request closed without merging**
