### PR TITLE
feat: Add setDeviceId method on web

### PR DESCRIPTION
**Pull request by dganzella**
Added setDeviceId method, so the output speaker (HTML5AudioElement sink ID) can be set -- so developer can select which device to play sound instead of default

### CODE REVIEW

**Comment by ryanheise** [comment]
I would suggest renaming this to `setWebDeviceId` following the convention of `setWebCrossOrigin` since it is a web-specific method. Or given that it's specific to the web API, maybe `setWebSinkId` so there is no confusion about what it represents? If you're thinking of generic naming so that multiple platforms can implement it in a different way, I think there are too many platform differences in the way audio routing APIs are designed that this would not work. Maybe there is a similar notion in Android, but in just_audio it is again named `androidAudioSessionId` as it is unlikely Android's API works in a similar way to other platforms (for example, you don't set it, you listen to it and then pass it into separate APIs for routing.)

**Comment by dganzella** [comment]
> I would suggest renaming this to `setWebDeviceId` following the convention of `setWebCrossOrigin` since it is a web-specific method. Or given that it's specific to the web API, maybe `setWebSinkId` so there is no confusion about what it represents? If you're thinking of generic naming so that multiple platforms can implement it in a different way, I think there are too many platform differences in the way audio routing APIs are designed that this would not work. Maybe there is a similar notion in Android, but in just_audio it is again named `androidAudioSessionId` as it is unlikely Android's API works in a similar way to other platforms (for example, you don't set it, you listen to it and then pass it into separate APIs for routing.)

k, I will fix it this week and send to you

**Comment by ryanheise** [comment]
Did you have an opinion on `setWebDeviceId` vs `setWebSinkId`? I think "sink" is more faithful to the original API.

**Comment by dganzella** [comment]
> Did you have an opinion on `setWebDeviceId` vs `setWebSinkId`? I think "sink" is more faithful to the original API.

Yes, I also think setWebSinkId is better!

**Comment by ryanheise** [comment]
Then let's go with the `setWebSinkId` naming, and then I can merge and release.

**Comment by dganzella** [comment]
ok @ryanheise I moved this PR to another, because I needed to revert the pubspec.yaml but did not want to change  the code that is working in production to stop compiling

https://github.com/ryanheise/just_audio/pull/1378

**Pull request closed without merging**
