### PR TITLE
[Fix] No podspec found for `just_audio_web` in `.symlinks/plugins/just_audio_web/ios`

### LINKED ISSUE #238: Example won't build, fails with "[!] No podspec found for `just_audio_web` in `.symlinks/plugins/just_audio_web/ios`"
**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.

**Minimal reproduction project**
Provide a link here using one of two options:
1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
2. If the unmodified official example already reproduces the bug, just write "The example".
The example

**To Reproduce (i.e. user steps, not code)**
1. Click to 'New Flutter Project" in Android Studio and create a new app
2. Add "just_audio: ^0.5.5" to the pubspec.yaml and do a pubspec get
3. Replace lib/main.dart with the example
4. Open ios Simulator for iPhone 12 Pro Max running ios 14.1 from xcode 12.1
5. Run the app in the simulator
6. xcode build fails

**Error messages**

```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...                                              1.0s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `audio_session` from `.symlinks/plugins/audio_session/ios`
    -> Fetching podspec for `just_audio` from `.symlinks/plugins/just_audio/ios`
    -> Fetching podspec for `just_audio_web` from `.symlinks/plugins/just_audio_web/ios`
    [!] No podspec found for `just_audio_web` in `.symlinks/plugins/just_audio_web/ios`

    /usr/local/Cellar/cocoapods/1.8.4/libexec/gems/cocoapods-1.8.4/lib/cocoapods/external_sources/path_source.rb:14:in `block in fetch'
    /usr/local/Cellar/cocoapods/1.8.4/libexec/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.8.4/libexec/gems/cocoapods-1.8.4/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
    /usr/local/Cellar/cocoapods/1.8.4/libexec/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:901:in `fetch_external_source'
    /usr/local/Cellar/cocoapods/1.8.4/libexec/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:880:in `block (2 levels) in fetch_external_sources'
    /usr/local/Cellar/cocoapods/1.8.4/libexec/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:879:in `each'
    /usr/local/Cellar/cocoapods/1.8.4/libexec/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:879:in `block in fetch_external_sources'
    /usr/local/Cellar/cocoapods/1.8.4/libexec/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.8.4/libexec/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:878:in `fetch_external_sources'
    /usr/local/Cellar/cocoapods/1.8.4/libexec/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
    /usr/local/Cellar/cocoapods/1.8.4/libexec/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
    /usr/local/Cellar/cocoapods/1.8.4/libexec/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.8.4/libexec/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.8.4/libexec/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.8.4/libexec/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
    /usr/local/Cellar/cocoapods/1.8.4/libexec/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.8.4/libexec/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.8.4/libexec/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.8.4/libexec/bin/pod:23:in `load'
    /usr/local/Cellar/cocoapods/1.8.4/libexec/bin/pod:23:in `<main>'

Error running pod install
Error launching application on iPhone 12 Pro Max.

```

**Expected behavior**
The example should run

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version] MacOS 10.15.7
 - Browser [e.g. chrome, safari + version] Chrome

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 12 Pro Max (Simulator)
 - OS: [e.g. iOS8.1] 14.1

**Flutter SDK version**
```

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
lits-tcerven:flutter_autdio_stake tomc$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.7 19H2, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Chrome - develop for the web
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2019.2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.34.0)
 
[✓] Connected device (3 available)            

! Doctor found issues in 2 categories.

```

**Additional context**

### PR DESCRIPTION
**Pull request by timilehinjegede**
Fixes #238

### CODE REVIEW

**Comment by ryanheise** [comment]
Ah, that would definitely be it. I must have been blind to have missed it! Thanks :-)

**Comment by siloebb** [comment]
Please, update the version of `just_audio_platform_interface` and `just_audio_web`in the main package, will help a lot.
The error continues because `just_audio_web` are in old version.

**Comment by ryanheise** [comment]
The next release is just waiting on testing.

If you would like to help with the testing, please consider checking out the latest version of just_audio and trying out the new features #246 and #249 .

**Comment by siloebb** [comment]
Nice, thank you, I just want to ask don't forgot to update the `just_audio_web` in the pub.
Thanks for all.

**Comment by ryanheise** [comment]
0.6.0 is now released. Let me know if you notice any issues with it.

**Pull request merged**
