### PR TITLE
Swift implementation (IOS Equalizer)

### PR DESCRIPTION
**Pull request by SimoneBressan**
I have opened this PR to trace the development of the implementation in swift and to give the possibility to use the equalizer in both platforms.

It is not stable and it is not complete. Any contribution is welcome. This branch originated from:
https://github.com/wavy-assistant/just_audio/tree/feature/new_ios_implementation

RelatedIssue: https://github.com/ryanheise/just_audio/issues/334

Basic Features:
- [x] `play`
- [x] `pause`
- [ ] `stop`
- [x] `seek` `seekToNext` `seekToPrevious`
- [x] `setVolume`
- [ ] `setSkipSilenceEnabled`
- [x] `setSpeed`
- [x] `setLoopMode`
- [x] `setShuffleModeEnabled`
- [ ] `shuffle`
- [ ] `setAutomaticallyWaitsToMinimizeStalling`
- [ ] `setCanUseNetworkResourcesForLiveStreamingWhilePaused`
- [ ] `setClip`
- [ ] `setPitch`
- [ ] `setPreferredPeakBitRate`

Media Supports:
- [ ] Assets
- [x] Ipod-library
- [ ] Web url
- [x] Local file

Equalizer:
- [x] Ios
- [x] Android

Extra:
- [x] Support switch output device

### CODE REVIEW

**Comment by BreX900** [comment]
@ryanheise Not all I undertake are mine. Those from AudioKit aren't mine. They are derived from the branch which was linked in the issue.
However, I admit that I tried to use but I couldn't. I just couldn't get it properly added to dependencies (pods) and therefore couldn't run the app. (I'm not a magician with swift and pods, sorry)

I needed a player with an equalizer and this seemed like the simplest solution, continue the implementation in swift.
So I decided to share my work but I don't think I will complete it with all the just_audio specifications but only the ones that need

**Comment by ryanheise** [comment]
Oops, it seems that when I renamed the `dev` branch to `major`, this PR got automatically closed. And unfortunately I can't edit it (as I normally can) to re-base it on `major`. Would you mind doing that on your end?

**Comment by ahmedalshakkaki** [comment]
I'm very lost here trying I've been trying to implement the equalizer to my project, it runs perfectly on Android but I couldn't figure out the way to make it work on IOS can you please share any kind of instructions on where to start to implement this on IOS, 
PS: thank you for the great work

**Comment by ryanheise** [comment]
Replaced by #784

**Pull request closed without merging**
