### PR TITLE
FIX: Unhandled Exception: type 'Null' is not a subtype of type 'MediaItem' in type cast

### PR DESCRIPTION
**Pull request by goviral-ma**
Unhandled Exception: type 'Null' is not a subtype of type 'MediaItem' in type cast

### CODE REVIEW

**Comment by otabekoff** [comment]
I think I am also getting this error when trying to use `just_audio_cache` with `just_audio` and `just_audio_background` packages together. I have predefined data and when I want to set them into a MediaItem it is giving "[Unhandled Exception: type 'Null' is not a subtype of type 'MediaItem' in type cast](https://github.com/ryanheise/just_audio/pull/1072#top) error. I thought it was happening by me. But it was the error gotten by others too. Please, fix this problem. As for now I am using type casting like `state........data.get as MediaItem(.....` as a workaround.

**Comment by otabekoff** [comment]
I my opinion, these changes by @goviral-ma doesn't fix errors at all.  Any further fixes @ryanheise ???

**Comment by otabekoff** [comment]
@goviral-ma I tested the reason why it is happening. When I removed `dynamicSet` part from `init`, it began to work. I mean it is issue with `just_audio_cache` plugin which is not owned by Ryan Heise.

**Comment by goviral-ma** [comment]
@otabekoff in my case I'm not using `just_audio_cache`
I'm using `just_audio` with `just_audio_background`, and this is a quick fix that worked for me and solved my problem.
The function `setClip` in just_audio doesn't take tag as parameter, and in the core of the function, an instance of `ClippingAudioSource` is created with null as tag variable, that's why the problem produced.

I simply solved it by adding tag variable to `setClip` to pass the value of tag to the function.

**Comment by otabekoff** [comment]
@goviral-ma So caching is working for you?

**Comment by mathisfouques** [comment]
Hey @otabekoff , in this [file](https://github.com/lau1944/just_audio_cache/blob/main/lib/src/audio_player_utils.dart), dynamicSet method use setFilePath from just_audio package. In this method [setFilePath](https://github.com/ryanheise/just_audio/blob/6952be55c6ddfb01f2567c0737ef098d1bd9fd45/just_audio/lib/just_audio.dart#L701), you see that AudioSource.file() does not set the tag, which is also added in this PR (but for setClip method). 

I've come up with this message because I had the same problem, but using just_audio + just_audio_background, with the setFilePath method, which, as setClip, does not set the tag used in just_audio_background. 

If you're just using just_audio + [...]_background with setFilePath, consider manually setting a tag as MediaItem to solve this : 
```
await player.setFilePath(path);

await player.setAudioSource(AudioSource.file(path,
  tag: MediaItem(
   id: path,
   title: path.split('/').last,
)));
```

Anyway, I think this notion of tag is not clear. I'm not sure if the value of the tag can ever NOT be a MediaItem, and if not we should consider removing the dynamic typing by MediaItem? . And even remove the nullable and put a default value ?
@ryanheise thoughts ? I can put another PR if you want.

**Comment by ryanheise** [comment]
First, thanks for bumping this, since it went off my radar. The tag is for associating your app's own data with each audio source. It's similar to Android's [View tags](https://developer.android.com/reference/android/view/View#tags). Any data structure can be stored in it. If you use just_audio_background, then you are letting that plugin manage the tag for you, so you don't get a choice, it has to be MediaItem. But if you want to manage things yourself, you should not use just_audio_background (i.e. use audio_service directly), and then you can use the tag to store whatever data you find useful.

Regarding the PR, yes this is important, and I agree the tag parameter probably needs to be added to a number of other places as well.

**Comment by mathisfouques** [comment]
Ok, here is the PR #1219 (@ryanheise)

**Comment by ryanheise** [comment]
Thanks, @goviral-ma for the contribution. This is now merged into `minor` along with #1219 for the other missing ones.

**Pull request merged**
