### PR TITLE
[Fix] preferPreciseDurationAndTiming config unused in file Uri

### PR DESCRIPTION
**Pull request by canxin121**
Related: #440 

Already tested in my app, using flac with file Uri, the position after seek is correct.

### CODE REVIEW

**Comment by canxin121** [comment]
@ryanheise Please review this pr.🤖

**Comment by ryanheise** [comment]
I'm not sure if it is possible to test this. It looks like only the Objective C code is updated but there is no way to pass in this option from Dart.

**Comment by canxin121** [comment]
>  I'm not sure if it is possible to test this. It looks like only the Objective C code is updated but there is no way to pass in this option from Dart.

> image https://github.com/canxin121/app_rhyme/actions/runs/8952578137
> 
> I used my fork to build my app in the lateset action, and tested it on my iphone13, works well.
> 
> The way to pass this configuration item remains exactly the same as before. Simply use:
> 
> ```dart
> ProgressiveAudioSource(
>     MusicUri,
>     tag: toMediaItem(),
>     options: const ProgressiveAudioSourceOptions(
>         darwinAssetOptions:
>             DarwinAssetOptions(preferPreciseDurationAndTiming: true)
>     )
> )
> ```
> 
> The function `createPlayerItem` previously ignored all configuration options for file type URI. This pull request simply reintroduces the use of the `preferPreciseDurationAndTiming` configuration option in file type URI.

**Comment by ryanheise** [comment]
Ah, sorry I misunderstood at first glance. You aren't adding a new option, you're just moving the activation of the existing option to work for local files as well.

**Comment by canxin121** [comment]
I recommend merging this PR, this simple change had no side effects during my testing

**Comment by ryanheise** [comment]
Thank you for contributing, @canxin121 . This is now merged into `minor` (edit: removing response about comments/assertions which were for another PR).

**Pull request merged**
