### PR TITLE
Add cross origin setting to HTML5 AudioElement

### PR DESCRIPTION
**Pull request by danielwinkler**
**Is your feature request related to a problem? Please describe.**

Currently there is no support for headers in the just audio web player

One way to use authenticated audio sources on the web are using authentication cookies.

If the audio is served from a different origin than the website, this is considered a cross origin request.

In order to allow sending the credentials along with such a request, the audio element has a crossorigin attribute, see

[https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin)

**Describe the solution you'd like**

This PR attempts to allow setting this attribute on the `HTML5AudioPlayer` class.

**Describe alternatives you've considered**

Another valid option would be a constructer that accepts an `AudioElement`, such that the attribute can be set before passing it to just_audio.
The other option would be to expose the `_audioElement` with a getter.

**Additional context**

Given the current encapsulation, the `_audioElement` cannot be accessed, if we had a getter around it the following test could be added to the PR

```dart
import 'package:test/test.dart';
import 'package:just_audio_web/just_audio_web.dart';

void main() {
  group('Html5AudioPlayer', () {
    late Html5AudioPlayer player;

    setUp(() {
      player = Html5AudioPlayer(id: 'test_player');
    });

    test('should set anonymous', () {
      final request =
          SetCrossOriginRequest(crossOrigin: CrossOriginMessage.anonymous);
      player.setCrossOrigin(request);
      expect(player.audioElement.attributes['crossOrigin'], 'anonymous');
    });

    test('should set use credentials', () {
      final request =
          SetCrossOriginRequest(crossOrigin: CrossOriginMessage.useCredentials);
      player.setCrossOrigin(request);
      expect(player.audioElement.attributes['crossOrigin'], 'use-credentials');
    });
  });
}
```

### CODE REVIEW

**Comment by ryanheise** [comment]
Hi @danielwinkler 

Any new methods need to be added to the platform interface and then implemented in just_audio_web (even though this is a web specific API).

Another design could just be to just pass this through the existing headers API, and in the web implementation pull these headers out and translate them into a `setCrossOrigin` call.

I'm not suggesting that's better or worse, but those would both work.

**Comment by danielwinkler** [comment]
Thanks for the feedback @ryanheise 

I added it to platform and prefixed `web`, I think the headers would be a bit confusing

To compile properly, I changed the ref in `pubspec.yaml` 

Do i have to split this to two PRs?

**Comment by ryanheise** [comment]
One more thing is that this is just the backend side of the plugin, so a user of just_audio won't be able to use this feature until there is a method in just_audio's AudioPlayer class. It can be implemented by simply delegating to the platform interface.

Regarding the temporary change to `pubspec.yaml`, keep that change locally, but commit the different `pubspec.yaml` files as they should appear in the final release. I'm not a fan of the complications the federated plugin model causes for the release process, and a two PR approach has been considered before, but I'm not currently doing that.

**Comment by danielwinkler** [comment]
Thanks a lot for the guidance @ryanheise 

I increased the version numbers everywhere starting from the platform interface

on the AudioPlayer level i exposed the web cors functionality as `setWebCrossOrigin(bool useCredentials)`

**Comment by ryanheise** [comment]
I think I will also be merging #1136 first given that wasm support has now entered flutter stable, and this may result in some conflicts unfortunately. I will let you know once I have done that.

**Comment by danielwinkler** [comment]
Sounds good!

Cheers,
daniel

ryanheise ***@***.***> schrieb am Do. 16. Mai 2024 um 16:55:

**Comment by ryanheise** [comment]
I've merged the other PR into minor now. By chance it looks like there are no merge conflicts, but you might want to test it to be sure. Note that the other PR already bumped just_audio_web to 0.4.10 and that's now released, so yours would need to be bumped to 0.4.11.

**Comment by danielwinkler** [comment]
Thanks for the update @ryanheise 

I updated the versions and added information to the README and changelog

**Comment by ryanheise** [comment]
I'll working through this now. I found some issues, but I'll sort them out. Mainly naming and docs.

**Comment by ryanheise** [comment]
I've made my changes in branch `feature/bump_web`. There are some name changes, and I've made the parameter in the main plugin into an enum to more directly reflect the underlying web API as well as making the parameter nullable so that you can "unset" the crossorigin attribute.

Not sure if you will see this in time but I will be publishing this imminently. The main thing that can't be changed is the API (once it's published), but if there are any bugs in the implementation of the platform interface, that can be fixed if you happen to find that what I've changed doesn't work for you.

**Comment by ryanheise** [comment]
This has now been released on pub.dev. Although it remains on the bump_web branch for now, until I fix an issue in just_audio_background.

**Comment by ryanheise** [comment]
I've updated just_audio_background to support this method. It is just released, and this branch is now merged. Thanks for your contribution. If you get a chance, you might want to review the changes I've made to understand what has changed.

**Pull request merged**
