### PR TITLE
Exoplayer exceptions

### PR DESCRIPTION
**Pull request by terryBaz**
- pump Expo player exceptions to flutter (android) https://github.com/ryanheise/just_audio/issues/31
- fix `.gitignore`
- update `Readme`
- code reformat `AudioPlayer.java`

### CODE REVIEW

**Comment by ryanheise** [comment]
Thanks! I'll check it out. Note that the Java files in this project use tabs rather than spaces for indentation. For the purposes of helping me to examine the diffs, could you undo the switch to spaces?

**Comment by terryBaz** [comment]
> Thanks! I'll check it out. Note that the Java files in this project use tabs rather than spaces for indentation. For the purposes of helping me to examine the diffs, could you undo the switch to spaces?

done, I reformatted using tabs

**Comment by ryanheise** [comment]
Thanks, I've now had a chance to review the code, and the solution looks good. Much appreciated.

Although the diffs do still contain a lot of other changes to my coding standards:

https://github.com/ryanheise/just_audio/pull/76/files

(I do want to keep my coding standards, and would prefer them not to be changed in a PR if possible :wink:)

Would you mind checking the above diff and undoing any formatting code changes changes? (i.e. switch cases and typecasts).

**Comment by terryBaz** [comment]
> Thanks, I've now had a chance to review the code, and the solution looks good. Much appreciated.
> 
> Although the diffs do still contain a lot of other changes to my coding standards:
> 
> https://github.com/ryanheise/just_audio/pull/76/files
> 
> (I do want to keep my coding standards, and would prefer them not to be changed in a PR if possible 😉)
> 
> Would you mind checking the above diff and undoing any formatting code changes changes? (i.e. switch cases and typecasts).

I undo the code format, but I believe that you should use a common formatting standard (or specify which standard you are using, you could share the config of you IDE) so that contributing will be more smother.
Thank you! for the package :D

**Comment by ryanheise** [comment]
Thanks, @terryBaz 

Call me "old school" on switch statements: https://www.oracle.com/java/technologies/javase/codeconventions-statements.html#468

While I don't necessarily agree with changing the coding standards, I'm not in principle against considering a change in the future. I just wouldn't want to change the coding style of an existing project within a PR for a different purpose. So if it is to be done, I'd prefer a PR to just change the lines relevant to the feature, and perhaps a separate PR for a coding style change, if that makes sense.

In any case, the diffs of your PR are definitely much easier to read and review now which I greatly appreciate.

**Comment by ryanheise** [comment]
Just merged!

**Pull request merged**
